name: Create Release Build

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog'     
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug
      
    - name: extract version code and version name
      run: |
        echo "VERSION_NAME="$(grep "versionName" app/build.gradle | awk '{print $2}' | sed 's/"//g') >> $GITHUB_ENV
        echo "VERSION_CODE="$(grep "versionCode" app/build.gradle | awk '{print $2}') >> $GITHUB_ENV
        
    - name: create tag and release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_CODE }}
        name: ${{ env.VERSION_NAME }}
        body: ${{ github.event.inputs.changelog }}
        files: app/build/outputs/apk/debug/app-debug.apk


